name: Build Plugins and Commit
run-name: Build Plugins and Commit
on:
  workflow_dispatch:  # manual trigger only
permissions:
  contents: write  # allow pushing commits
jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install -r requirements.txt  # if needed
      - name: Run build script
        run: python scripts/build_plugins.py
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            # Ensure we push to the same branch we checked out
            branch="$(git rev-parse --abbrev-ref HEAD)"
            git commit -m "Automated build: update plugins"
            git push origin "$branch"
          fi